spring.application.name=blogging

spring.datasource.url=jdbc:mysql://localhost:3306/blogging
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto=update